name: Build

on:
  push:
    branches:
      - master
      - neworigins
  workflow_dispatch:
  pull_request:

jobs:
  compile:
    name: Complie
    runs-on: ${{ format('{0}-latest', matrix.os) }}
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
        include:
           - os: windows
             ext: .exe
    steps:
      - uses: actions/checkout@v2
      - run: make all-clean && make all
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
              basic/basic${{ matrix.ext }}
              fracas/fracas${{ matrix.ext }}
              havilah/havilah${{ matrix.ext }}
              kingdoms/kingdoms${{ matrix.ext }}
              neworigins/neworigins${{ matrix.ext }}
              standard/standard${{ matrix.ext }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ubuntu
      - run: ./run-tests.sh
        working-directory: tests
