name: Build

on:
  push:
    branches:
      - master
      - neworigins
      - neworigins-v6
      - jt-*
  workflow_dispatch:
  pull_request:

jobs:
  compile:
    name: Compile
    runs-on: ${{ format('{0}-latest', matrix.os) }}
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
        include:
           - os: windows
             ext: .exe
    steps:
      - uses: actions/checkout@v4
      - run: make all-clean && make all
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
              basic/basic${{ matrix.ext }}
              fracas/fracas${{ matrix.ext }}
              havilah/havilah${{ matrix.ext }}
              kingdoms/kingdoms${{ matrix.ext }}
              neworigins/neworigins${{ matrix.ext }}
              standard/standard${{ matrix.ext }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu
      - run: ./run-snapshots.sh
        working-directory: snapshot-tests

  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make unittest
      - run: ./unittest
        working-directory: unittest
