name: Atlantis C/C++ CI Master Branch

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@master
    - name: make all
      run: make all
