name: Atlantis C/C++ CI Monthly Master Branch

on:
  schedule:
  - cron:  0 0 1 * *

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: make all
      run: make all
